[package]
name = "devhands_ws"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
config = "0.13"
dotenv = "0.15"
serde_json = "1.0.140"
hex = "0.4.3"
md5 = "0.7.0"